version: '3.8'

services:

  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Set the active profile; adjust as necessary
    networks:
      - app-net

networks:
  app-net: