version: '3'
services:
  application:
    container_name: eum-gateway
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - eum-gateway

networks:
  eum-gateway:
