
server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://223.130.146.39:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8888
      name: msa-architecture-config-server
      enabled: false
    gateway:
      routes:
        - id: haetsal-service
          uri: http://localhost:8000
          predicates:
            - Path=/haetsal-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthUserAuthorizationHeaderFilter
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth-service/api/v2/auth/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-service
          uri: http://localhost:8000/
          predicates:
            - Path=/auth-service/api/v2/profile
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - TemptUserAuthorizationHeaderFilter
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth-service/api/v2/logOut
          filters:
            - RemoveRequestHeader=Cookie
            - TemptUserAuthorizationHeaderFilter
        - id: chat-service
          uri: http://223.130.141.109:5000/
          predicates:
            - Path=/chat-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthUserAuthorizationHeaderFilter