
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8888
      name: msa-architecture-config-server
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true # JWT 나 쿠키를 사용해 메시지를 보내야 할 경우 true
            allowedHeaders: '*'
            allowedMethods: 
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring cloud gateway Global Filter
            preLogger: true
            postLogger: true

      routes:
        - id: haetsal-service
          uri: http://localhost:80
          predicates:
            - Path=/haetsal-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthUserAuthorizationHeaderFilter
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth-service/api/v2/auth/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-service
          uri: http://localhost:80/
          predicates:
            - Path=/auth-service/api/v2/profile
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - TemptUserAuthorizationHeaderFilter
