on:
  push:
    branches: [ dev-test ]

jobs:
  deploy:
    runs-on: self-hosted	# self-hosted 로 변경 (macOS라고 작성해도 상관없습니다.)

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17