
on:
  push:
    branches:
      - 'dev-test'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2
        with:
          ref: server/deploy

      - name: Change Directory and Docker compose
        run: |                                                                                        
          sudo docker compose up -d --build